services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./backend:/usr/src/app
      - profile-uploads:/usr/src/app/uploads/profiles
    depends_on:
      - mongo
    entrypoint: ["node", "server.js"]
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - APP_API_URL=${APP_API_URL}
      - APP_ENV=${APP_ENV}
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  profile-uploads:

networks:
  app-network:
    driver: bridge
